<?php
$this->headTitle('Users');

//$this->mainMenu()->setActiveItemId('users');
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Users'=>$this->url('users'),
//            ]);
?>

<h1>Manage Users</h1>

<p>
    <a class="btn btn-success" href="
       <?= $this->url('users', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Date Created</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>

    <?php foreach ($users as $user): ?>

        <tr>
            <td><?= $this->escapeHtml($user->getId()); ?></td>
            <td>
                <a href="<?= $this->url('users', ['action' => 'view', 'id' => $user->getId()]); ?>">
                    <?= $this->escapeHtml($user->getEmail()); ?>
                </a> 
            </td>
            <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
            </td>
            <td><?= $this->escapeHtml($user->getDateCreated()->format('d/m/Y H:i:s')); ?></td>        
            <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
            <td class="float-right">
                <div class="btn-group">
                    <a class="btn btn-info" href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->getId()]);
                    ?>">
                        <span class="fa fa-pencil" ></span>
                    </a>
                    <a class="btn btn-info" href="<?= $this->url('users', ['action' => 'change-password', 'id' => $user->getId()]);
                    ?>">
                        <span class="fa fa-lock"></span>
                    </a>
                </div>
            </td>    
        </tr>

    <?php endforeach; ?>   

</table>

