<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'E-mail',
    'required' => true,
    'autofocus' => true,
    'id' => 'inputEmail',
    'aria-describedby' => 'emailHelp',
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Senha',
    'required' => true,
]);

$form->get('remember_me')->setAttributes([
   'class' => 'form-check-input', 
]);
?>
<div class="card w-25 mx-auto mt-5">
    <div class="card-body text-center">
        <i class="fas fa-user-lock fa-3x"></i>
        <form class="form text-left mt-5" method="post">
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Usuário e/ou senha incorretos.
                </div>
            <?php endif; ?>
            <span id="reauth-email" class="reauth-email"></span>
            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('password')); ?>
                <?= $this->formElement($form->get('password')); ?>
            </div>
            <div class="form-group form-check">
                <?= $this->formCheckbox($form->get('remember_me')); ?>
                <?= $this->formLabel($form->get('remember_me')); ?>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <?= $this->formElement($form->get('submit')); ?>
        </form>
        <a href="<?=$this->url('reset-password');?>" class="float-right"> Esqueceu sua senha?</a>
    </div>
</div>
