<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Dartalla')->setSeparator(' - ')->setAutoEscape(false) ?>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('dartalla/css/dtl-login.css'))
                ->prependStylesheet($this->basePath('fontawesome/css/all.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
                ->prependFile($this->basePath('bower_components/jquery/dist/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row dtl-app">
                <div class="col-10 dtl-app-content mx-auto">
                    <?= $this->content ?>
                </div>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
